using FlagExplorer.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using static System.Net.WebRequestMethods;
using System.Drawing;
using System.Net.NetworkInformation;

namespace FlagExplorer.Infrastructre.Data
{
    public class FlagExplorerContext : DbContext
    {
        public DbSet<Country> Countries { get; set; }

        public FlagExplorerContext(DbContextOptions options) : base(options) { }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Country>().HasData(
                new Country { Id = 1, Name = "South Georgia", Population = 30, Capital = "King Edward Point", Flag = "https://flagcdn.com/w320/gs.png" },
                                new Country { Id = 2, Name = "Grenada", Population = 112519, Capital = "St. George's", Flag = "https://flagcdn.com/w320/gd.png" },
                                new Country { Id = 3, Name = "Switzerland", Population = 8654622, Capital = "Bern", Flag = "https://flagcdn.com/w320/ch.png" },
                                new Country { Id = 4, Name = "Sierra Leone", Population = 7976985, Capital = "Freetown", Flag = "https://flagcdn.com/w320/sl.png" },
                                new Country { Id = 5, Name = "Hungary", Population = 9749763, Capital = "Budapest", Flag = "https://flagcdn.com/w320/hu.png" },
                                new Country { Id = 6, Name = "Taiwan", Population = 23503349, Capital = "Taipei", Flag = "https://flagcdn.com/w320/tw.png" },
                                new Country { Id = 7, Name = "Wallis and Futuna", Population = 11750, Capital = "Mata-Utu", Flag = "https://flagcdn.com/w320/wf.png" },
                                new Country { Id = 8, Name = "Barbados", Population = 287371, Capital = "Bridgetown", Flag = "https://flagcdn.com/w320/bb.png" },
                                new Country { Id = 9, Name = "Pitcairn Islands", Population = 56, Capital = "Adamstown", Flag = "https://flagcdn.com/w320/pn.png" },
                                new Country { Id = 10, Name = "Ivory Coast", Population = 26378275, Capital = "Yamoussoukro", Flag = "https://flagcdn.com/w320/ci.png" },
                                new Country { Id = 11, Name = "Tunisia", Population = 11818618, Capital = "Tunis", Flag = "https://flagcdn.com/w320/tn.png" },
                                new Country { Id = 12, Name = "Italy", Population = 59554023, Capital = "Rome", Flag = "https://flagcdn.com/w320/it.png" },
                                new Country { Id = 13, Name = "Benin", Population = 12123198, Capital = "Porto-Novo", Flag = "https://flagcdn.com/w320/bj.png" },
                                new Country { Id = 14, Name = "Indonesia", Population = 273523621, Capital = "Jakarta", Flag = "https://flagcdn.com/w320/id.png" },
                                new Country { Id = 15, Name = "Cape Verde", Population = 555988, Capital = "Praia", Flag = "https://flagcdn.com/w320/cv.png" },
                                new Country { Id = 16, Name = "Saint Kitts and Nevis", Population = 53192, Capital = "Basseterre", Flag = "https://flagcdn.com/w320/kn.png" },
                                new Country { Id = 17, Name = "Laos", Population = 7275556, Capital = "Vientiane", Flag = "https://flagcdn.com/w320/la.png" },
                                new Country { Id = 18, Name = "Caribbean Netherlands", Population = 25987, Capital = "Kralendijk", Flag = "https://flagcdn.com/w320/bq.png" },
                                new Country { Id = 19, Name = "Uganda", Population = 45741000, Capital = "Kampala", Flag = "https://flagcdn.com/w320/ug.png" },
                                new Country { Id = 20, Name = "Andorra", Population = 77265, Capital = "Andorra la Vella", Flag = "https://flagcdn.com/w320/ad.png" },
                                new Country { Id = 21, Name = "Burundi", Population = 11890781, Capital = "Gitega", Flag = "https://flagcdn.com/w320/bi.png" },
                                new Country { Id = 22, Name = "South Africa", Population = 59308690, Capital = "Pretoria", Flag = "https://flagcdn.com/w320/za.png" },
                                new Country { Id = 23, Name = "France", Population = 67391582, Capital = "Paris", Flag = "https://flagcdn.com/w320/fr.png" },
                                new Country { Id = 24, Name = "Libya", Population = 6871287, Capital = "Tripoli", Flag = "https://flagcdn.com/w320/ly.png" },
                                new Country { Id = 25, Name = "Mexico", Population = 128932753, Capital = "Mexico City", Flag = "https://flagcdn.com/w320/mx.png" },
                                new Country { Id = 26, Name = "Gabon", Population = 2225728, Capital = "Libreville", Flag = "https://flagcdn.com/w320/ga.png" },
                                new Country { Id = 27, Name = "Northern Mariana Islands", Population = 57557, Capital = "Saipan", Flag = "https://flagcdn.com/w320/mp.png" },
                                new Country { Id = 28, Name = "North Macedonia", Population = 2077132, Capital = "Skopje", Flag = "https://flagcdn.com/w320/mk.png" },
                                new Country { Id = 29, Name = "China", Population = 1402112000, Capital = "Beijing", Flag = "https://flagcdn.com/w320/cn.png" },
                                new Country { Id = 30, Name = "Yemen", Population = 29825968, Capital = "Sana'a", Flag = "https://flagcdn.com/w320/ye.png" },
                                new Country { Id = 31, Name = "Saint Barthélemy", Population = 4255, Capital = "Gustavia", Flag = "https://flagcdn.com/w320/bl.png" },
                                new Country { Id = 32, Name = "Guernsey", Population = 62999, Capital = "St. Peter Port", Flag = "https://flagcdn.com/w320/gg.png" },
                                new Country { Id = 33, Name = "Solomon Islands", Population = 686878, Capital = "Honiara", Flag = "https://flagcdn.com/w320/sb.png" },
                                new Country { Id = 34, Name = "Svalbard and Jan Mayen", Population = 2562, Capital = "Longyearbyen", Flag = "https://flagcdn.com/w320/sj.png" },
                                new Country { Id = 35, Name = "Faroe Islands", Population = 48865, Capital = "Tórshavn", Flag = "https://flagcdn.com/w320/fo.png" },
                                new Country { Id = 36, Name = "Uzbekistan", Population = 34232050, Capital = "Tashkent", Flag = "https://flagcdn.com/w320/uz.png" },
                                new Country { Id = 37, Name = "Egypt", Population = 102334403, Capital = "Cairo", Flag = "https://flagcdn.com/w320/eg.png" },
                                new Country { Id = 38, Name = "Senegal", Population = 16743930, Capital = "Dakar", Flag = "https://flagcdn.com/w320/sn.png" },
                                new Country { Id = 39, Name = "Sri Lanka", Population = 21919000, Capital = "Sri Jayawardenepura Kotte", Flag = "https://flagcdn.com/w320/lk.png" },
                                new Country { Id = 40, Name = "Palestine", Population = 4803269, Capital = "Ramallah", Flag = "https://flagcdn.com/w320/ps.png" },
                                new Country { Id = 41, Name = "Bangladesh", Population = 164689383, Capital = "Dhaka", Flag = "https://flagcdn.com/w320/bd.png" },
                                new Country { Id = 42, Name = "Peru", Population = 32971846, Capital = "Lima", Flag = "https://flagcdn.com/w320/pe.png" },
                                new Country { Id = 43, Name = "Singapore", Population = 5685807, Capital = "Singapore", Flag = "https://flagcdn.com/w320/sg.png" },
                                new Country { Id = 44, Name = "Turkey", Population = 84339067, Capital = "Ankara", Flag = "https://flagcdn.com/w320/tr.png" },
                                new Country { Id = 45, Name = "Afghanistan", Population = 40218234, Capital = "Kabul", Flag = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png" },
                                new Country { Id = 46, Name = "Aruba", Population = 106766, Capital = "Oranjestad", Flag = "https://flagcdn.com/w320/aw.png" },
                                new Country { Id = 47, Name = "Cook Islands", Population = 18100, Capital = "Avarua", Flag = "https://flagcdn.com/w320/ck.png" },
                                new Country { Id = 48, Name = "United Kingdom", Population = 67215293, Capital = "London", Flag = "https://flagcdn.com/w320/gb.png" },
                                new Country { Id = 49, Name = "Zambia", Population = 18383956, Capital = "Lusaka", Flag = "https://flagcdn.com/w320/zm.png" },
                                new Country { Id = 50, Name = "Finland", Population = 5530719, Capital = "Helsinki", Flag = "https://flagcdn.com/w320/fi.png" },
                                new Country { Id = 51, Name = "Niger", Population = 24206636, Capital = "Niamey", Flag = "https://flagcdn.com/w320/ne.png" },
                                new Country { Id = 52, Name = "Christmas Island", Population = 2072, Capital = "Flying Fish Cove", Flag = "https://flagcdn.com/w320/cx.png" },
                                new Country { Id = 53, Name = "Tokelau", Population = 1411, Capital = "Fakaofo", Flag = "https://flagcdn.com/w320/tk.png" },
                                new Country { Id = 54, Name = "Guinea-Bissau", Population = 1967998, Capital = "Bissau", Flag = "https://flagcdn.com/w320/gw.png" },
                                new Country { Id = 55, Name = "Azerbaijan", Population = 10110116, Capital = "Baku", Flag = "https://flagcdn.com/w320/az.png" },
                                new Country { Id = 56, Name = "Réunion", Population = 840974, Capital = "Saint-Denis", Flag = "https://flagcdn.com/w320/re.png" },
                                new Country { Id = 57, Name = "Djibouti", Population = 988002, Capital = "Djibouti", Flag = "https://flagcdn.com/w320/dj.png" },
                                new Country { Id = 58, Name = "North Korea", Population = 25778815, Capital = "Pyongyang", Flag = "https://flagcdn.com/w320/kp.png" },
                                new Country { Id = 59, Name = "Mauritius", Population = 1265740, Capital = "Port Louis", Flag = "https://flagcdn.com/w320/mu.png" },
                                new Country { Id = 60, Name = "Montserrat", Population = 4922, Capital = "Plymouth", Flag = "https://flagcdn.com/w320/ms.png" },
                                new Country { Id = 61, Name = "United States Virgin Islands", Population = 106290, Capital = "Charlotte Amalie", Flag = "https://flagcdn.com/w320/vi.png" },
                                new Country { Id = 62, Name = "Colombia", Population = 50882884, Capital = "Bogotá", Flag = "https://flagcdn.com/w320/co.png" },
                                new Country { Id = 63, Name = "Greece", Population = 10715549, Capital = "Athens", Flag = "https://flagcdn.com/w320/gr.png" },
                                new Country { Id = 64, Name = "Croatia", Population = 4047200, Capital = "Zagreb", Flag = "https://flagcdn.com/w320/hr.png" },
                                new Country { Id = 65, Name = "Morocco", Population = 36910558, Capital = "Rabat", Flag = "https://flagcdn.com/w320/ma.png" },
                                new Country { Id = 66, Name = "Algeria", Population = 44700000, Capital = "Algiers", Flag = "https://flagcdn.com/w320/dz.png" },
                                new Country { Id = 67, Name = "Antarctica", Population = 1000, Capital = "", Flag = "https://flagcdn.com/w320/aq.png" },
                                new Country { Id = 68, Name = "Netherlands", Population = 16655799, Capital = "Amsterdam", Flag = "https://flagcdn.com/w320/nl.png" },
                                new Country { Id = 69, Name = "Sudan", Population = 43849269, Capital = "Khartoum", Flag = "https://flagcdn.com/w320/sd.png" },
                                new Country { Id = 70, Name = "Fiji", Population = 896444, Capital = "Suva", Flag = "https://flagcdn.com/w320/fj.png" },
                                new Country { Id = 71, Name = "Liechtenstein", Population = 38137, Capital = "Vaduz", Flag = "https://flagcdn.com/w320/li.png" },
                                new Country { Id = 72, Name = "Nepal", Population = 29136808, Capital = "Kathmandu", Flag = "https://flagcdn.com/w320/np.png" },
                                new Country { Id = 73, Name = "Puerto Rico", Population = 3194034, Capital = "San Juan", Flag = "https://flagcdn.com/w320/pr.png" },
                                new Country { Id = 74, Name = "Georgia", Population = 3714000, Capital = "Tbilisi", Flag = "https://flagcdn.com/w320/ge.png" },
                                new Country { Id = 75, Name = "Pakistan", Population = 220892331, Capital = "Islamabad", Flag = "https://flagcdn.com/w320/pk.png" },
                                new Country { Id = 76, Name = "Monaco", Population = 39244, Capital = "Monaco", Flag = "https://flagcdn.com/w320/mc.png" },
                                new Country { Id = 77, Name = "Botswana", Population = 2351625, Capital = "Gaborone", Flag = "https://flagcdn.com/w320/bw.png" },
                                new Country { Id = 78, Name = "Lebanon", Population = 6825442, Capital = "Beirut", Flag = "https://flagcdn.com/w320/lb.png" },
                                new Country { Id = 79, Name = "Papua New Guinea", Population = 8947027, Capital = "Port Moresby", Flag = "https://flagcdn.com/w320/pg.png" },
                                new Country { Id = 80, Name = "Mayotte", Population = 226915, Capital = "Mamoudzou", Flag = "https://flagcdn.com/w320/yt.png" },
                                new Country { Id = 81, Name = "Dominican Republic", Population = 10847904, Capital = "Santo Domingo", Flag = "https://flagcdn.com/w320/do.png" },
                                new Country { Id = 82, Name = "Norfolk Island", Population = 2302, Capital = "Kingston", Flag = "https://flagcdn.com/w320/nf.png" },
                                new Country { Id = 83, Name = "Bouvet Island", Population = 0, Capital = "", Flag = "https://flagcdn.com/w320/bv.png" },
                                new Country { Id = 84, Name = "Qatar", Population = 2881060, Capital = "Doha", Flag = "https://flagcdn.com/w320/qa.png" },
                                new Country { Id = 85, Name = "Madagascar", Population = 27691019, Capital = "Antananarivo", Flag = "https://flagcdn.com/w320/mg.png" },
                                new Country { Id = 86, Name = "India", Population = 1380004385, Capital = "New Delhi", Flag = "https://flagcdn.com/w320/in.png" },
                                new Country { Id = 87, Name = "Syria", Population = 17500657, Capital = "Damascus", Flag = "https://flagcdn.com/w320/sy.png" },
                                new Country { Id = 88, Name = "Montenegro", Population = 621718, Capital = "Podgorica", Flag = "https://flagcdn.com/w320/me.png" },
                                new Country { Id = 89, Name = "Eswatini", Population = 1160164, Capital = "Mbabane", Flag = "https://flagcdn.com/w320/sz.png" },
                                new Country { Id = 90, Name = "Paraguay", Population = 7132530, Capital = "Asunción", Flag = "https://flagcdn.com/w320/py.png" },
                                new Country { Id = 91, Name = "El Salvador", Population = 6486201, Capital = "San Salvador", Flag = "https://flagcdn.com/w320/sv.png" },
                                new Country { Id = 92, Name = "Ukraine", Population = 44134693, Capital = "Kyiv", Flag = "https://flagcdn.com/w320/ua.png" },
                                new Country { Id = 93, Name = "Isle of Man", Population = 85032, Capital = "Douglas", Flag = "https://flagcdn.com/w320/im.png" },
                                new Country { Id = 94, Name = "Namibia", Population = 2540916, Capital = "Windhoek", Flag = "https://flagcdn.com/w320/na.png" },
                                new Country { Id = 95, Name = "United Arab Emirates", Population = 9890400, Capital = "Abu Dhabi", Flag = "https://flagcdn.com/w320/ae.png" },
                                new Country { Id = 96, Name = "Bulgaria", Population = 6927288, Capital = "Sofia", Flag = "https://flagcdn.com/w320/bg.png" },
                                new Country { Id = 97, Name = "Greenland", Population = 56367, Capital = "Nuuk", Flag = "https://flagcdn.com/w320/gl.png" },
                                new Country { Id = 98, Name = "Germany", Population = 83240525, Capital = "Berlin", Flag = "https://flagcdn.com/w320/de.png" },
                                new Country { Id = 99, Name = "Cambodia", Population = 16718971, Capital = "Phnom Penh", Flag = "https://flagcdn.com/w320/kh.png" },
                                new Country { Id = 100, Name = "Iraq", Population = 40222503, Capital = "Baghdad", Flag = "https://flagcdn.com/w320/iq.png" },
                                new Country { Id = 101, Name = "French Southern and Antarctic Lands", Population = 400, Capital = "Port-aux-Français", Flag = "https://flagcdn.com/w320/tf.png" },
                                new Country { Id = 102, Name = "Sweden", Population = 10353442, Capital = "Stockholm", Flag = "https://flagcdn.com/w320/se.png" },
                                new Country { Id = 103, Name = "Cuba", Population = 11326616, Capital = "Havana", Flag = "https://flagcdn.com/w320/cu.png" },
                                new Country { Id = 104, Name = "Kyrgyzstan", Population = 6591600, Capital = "Bishkek", Flag = "https://flagcdn.com/w320/kg.png" },
                                new Country { Id = 105, Name = "Russia", Population = 144104080, Capital = "Moscow", Flag = "https://flagcdn.com/w320/ru.png" },
                                new Country { Id = 106, Name = "Malaysia", Population = 32365998, Capital = "Kuala Lumpur", Flag = "https://flagcdn.com/w320/my.png" },
                                new Country { Id = 107, Name = "São Tomé and Príncipe", Population = 219161, Capital = "São Tomé", Flag = "https://flagcdn.com/w320/st.png" },
                                new Country { Id = 108, Name = "Cyprus", Population = 1207361, Capital = "Nicosia", Flag = "https://flagcdn.com/w320/cy.png" },
                                new Country { Id = 109, Name = "Canada", Population = 38005238, Capital = "Ottawa", Flag = "https://flagcdn.com/w320/ca.png" },
                                new Country { Id = 110, Name = "Malawi", Population = 19129955, Capital = "Lilongwe", Flag = "https://flagcdn.com/w320/mw.png" },
                                new Country { Id = 111, Name = "Saudi Arabia", Population = 34813867, Capital = "Riyadh", Flag = "https://flagcdn.com/w320/sa.png" },
                                new Country { Id = 112, Name = "Bosnia and Herzegovina", Population = 3280815, Capital = "Sarajevo", Flag = "https://flagcdn.com/w320/ba.png" },
                                new Country { Id = 113, Name = "Ethiopia", Population = 114963583, Capital = "Addis Ababa", Flag = "https://flagcdn.com/w320/et.png" },
                                new Country { Id = 114, Name = "Spain", Population = 47351567, Capital = "Madrid", Flag = "https://flagcdn.com/w320/es.png" },
                                new Country { Id = 115, Name = "Slovenia", Population = 2100126, Capital = "Ljubljana", Flag = "https://flagcdn.com/w320/si.png" },
                                new Country { Id = 116, Name = "Oman", Population = 5106622, Capital = "Muscat", Flag = "https://flagcdn.com/w320/om.png" },
                                new Country { Id = 117, Name = "Saint Pierre and Miquelon", Population = 6069, Capital = "Saint-Pierre", Flag = "https://flagcdn.com/w320/pm.png" },
                                new Country { Id = 118, Name = "Macau", Population = 649342, Capital = "", Flag = "https://flagcdn.com/w320/mo.png" },
                                new Country { Id = 119, Name = "San Marino", Population = 33938, Capital = "City of San Marino", Flag = "https://flagcdn.com/w320/sm.png" },
                                new Country { Id = 120, Name = "Lesotho", Population = 2142252, Capital = "Maseru", Flag = "https://flagcdn.com/w320/ls.png" },
                                new Country { Id = 121, Name = "Marshall Islands", Population = 59194, Capital = "Majuro", Flag = "https://flagcdn.com/w320/mh.png" },
                                new Country { Id = 122, Name = "Sint Maarten", Population = 40812, Capital = "Philipsburg", Flag = "https://flagcdn.com/w320/sx.png" },
                                new Country { Id = 123, Name = "Iceland", Population = 366425, Capital = "Reykjavik", Flag = "https://flagcdn.com/w320/is.png" },
                                new Country { Id = 124, Name = "Luxembourg", Population = 632275, Capital = "Luxembourg", Flag = "https://flagcdn.com/w320/lu.png" },
                                new Country { Id = 125, Name = "Argentina", Population = 45376763, Capital = "Buenos Aires", Flag = "https://flagcdn.com/w320/ar.png" },
                                new Country { Id = 126, Name = "Turks and Caicos Islands", Population = 38718, Capital = "Cockburn Town", Flag = "https://flagcdn.com/w320/tc.png" },
                                new Country { Id = 127, Name = "Nauru", Population = 10834, Capital = "Yaren", Flag = "https://flagcdn.com/w320/nr.png" },
                                new Country { Id = 128, Name = "Cocos (Keeling) Islands", Population = 544, Capital = "West Island", Flag = "https://flagcdn.com/w320/cc.png" },
                                new Country { Id = 129, Name = "Western Sahara", Population = 510713, Capital = "El Aaiún", Flag = "https://flagcdn.com/w320/eh.png" },
                                new Country { Id = 130, Name = "Dominica", Population = 71991, Capital = "Roseau", Flag = "https://flagcdn.com/w320/dm.png" },
                                new Country { Id = 131, Name = "Costa Rica", Population = 5094114, Capital = "San José", Flag = "https://flagcdn.com/w320/cr.png" },
                                new Country { Id = 132, Name = "Australia", Population = 25687041, Capital = "Canberra", Flag = "https://flagcdn.com/w320/au.png" },
                                new Country { Id = 133, Name = "Thailand", Population = 69799978, Capital = "Bangkok", Flag = "https://flagcdn.com/w320/th.png" },
                                new Country { Id = 134, Name = "Haiti", Population = 11402533, Capital = "Port-au-Prince", Flag = "https://flagcdn.com/w320/ht.png" },
                                new Country { Id = 135, Name = "Tuvalu", Population = 11792, Capital = "Funafuti", Flag = "https://flagcdn.com/w320/tv.png" },
                                new Country { Id = 136, Name = "Honduras", Population = 9904608, Capital = "Tegucigalpa", Flag = "https://flagcdn.com/w320/hn.png" },
                                new Country { Id = 137, Name = "Equatorial Guinea", Population = 1402985, Capital = "Malabo", Flag = "https://flagcdn.com/w320/gq.png" },
                                new Country { Id = 138, Name = "Saint Lucia", Population = 183629, Capital = "Castries", Flag = "https://flagcdn.com/w320/lc.png" },
                                new Country { Id = 139, Name = "French Polynesia", Population = 280904, Capital = "Papeete", Flag = "https://flagcdn.com/w320/pf.png" },
                                new Country { Id = 140, Name = "Belarus", Population = 9398861, Capital = "Minsk", Flag = "https://flagcdn.com/w320/by.png" },
                                new Country { Id = 141, Name = "Latvia", Population = 1901548, Capital = "Riga", Flag = "https://flagcdn.com/w320/lv.png" },
                                new Country { Id = 142, Name = "Palau", Population = 18092, Capital = "Ngerulmud", Flag = "https://flagcdn.com/w320/pw.png" },
                                new Country { Id = 143, Name = "Guadeloupe", Population = 400132, Capital = "Basse-Terre", Flag = "https://flagcdn.com/w320/gp.png" },
                                new Country { Id = 144, Name = "Philippines", Population = 109581085, Capital = "Manila", Flag = "https://flagcdn.com/w320/ph.png" },
                                new Country { Id = 145, Name = "Gibraltar", Population = 33691, Capital = "Gibraltar", Flag = "https://flagcdn.com/w320/gi.png" },
                                new Country { Id = 146, Name = "Denmark", Population = 5831404, Capital = "Copenhagen", Flag = "https://flagcdn.com/w320/dk.png" },
                                new Country { Id = 147, Name = "Cameroon", Population = 26545864, Capital = "Yaoundé", Flag = "https://flagcdn.com/w320/cm.png" },
                                new Country { Id = 148, Name = "Guinea", Population = 13132792, Capital = "Conakry", Flag = "https://flagcdn.com/w320/gn.png" },
                                new Country { Id = 149, Name = "Bahrain", Population = 1701583, Capital = "Manama", Flag = "https://flagcdn.com/w320/bh.png" },
                                new Country { Id = 150, Name = "Suriname", Population = 586634, Capital = "Paramaribo", Flag = "https://flagcdn.com/w320/sr.png" },
                                new Country { Id = 151, Name = "DR Congo", Population = 108407721, Capital = "Kinshasa", Flag = "https://flagcdn.com/w320/cd.png" },
                                new Country { Id = 152, Name = "Somalia", Population = 15893219, Capital = "Mogadishu", Flag = "https://flagcdn.com/w320/so.png" },
                                new Country { Id = 153, Name = "Czechia", Population = 10698896, Capital = "Prague", Flag = "https://flagcdn.com/w320/cz.png" },
                                new Country { Id = 154, Name = "New Caledonia", Population = 271960, Capital = "Nouméa", Flag = "https://flagcdn.com/w320/nc.png" },
                                new Country { Id = 155, Name = "Vanuatu", Population = 307150, Capital = "Port Vila", Flag = "https://flagcdn.com/w320/vu.png" },
                                new Country { Id = 156, Name = "Saint Helena", Population = 53192, Capital = "Ascension and Tristan da Cunha", Flag = "https://flagcdn.com/w320/sh.png" },
                                new Country { Id = 157, Name = "Togo", Population = 8278737, Capital = "Lomé", Flag = "https://flagcdn.com/w320/tg.png" },
                                new Country { Id = 158, Name = "British Virgin Islands", Population = 30237, Capital = "Road Town", Flag = "https://flagcdn.com/w320/vg.png" },
                                new Country { Id = 159, Name = "Kenya", Population = 53771300, Capital = "Nairobi", Flag = "https://flagcdn.com/w320/ke.png" },
                                new Country { Id = 160, Name = "Niue", Population = 1470, Capital = "Alofi", Flag = "https://flagcdn.com/w320/nu.png" },
                                new Country { Id = 161, Name = "Heard Island and McDonald Islands", Population = 0, Capital = "", Flag = "https://flagcdn.com/w320/hm.png" },
                                new Country { Id = 162, Name = "Rwanda", Population = 12952209, Capital = "Kigali", Flag = "https://flagcdn.com/w320/rw.png" },
                                new Country { Id = 163, Name = "Estonia", Population = 1331057, Capital = "Tallinn", Flag = "https://flagcdn.com/w320/ee.png" },
                                new Country { Id = 164, Name = "Romania", Population = 19286123, Capital = "Bucharest", Flag = "https://flagcdn.com/w320/ro.png" },
                                new Country { Id = 165, Name = "Trinidad and Tobago", Population = 1399491, Capital = "Port of Spain", Flag = "https://flagcdn.com/w320/tt.png" },
                                new Country { Id = 166, Name = "Guyana", Population = 786559, Capital = "Georgetown", Flag = "https://flagcdn.com/w320/gy.png" },
                                new Country { Id = 167, Name = "Timor-Leste", Population = 1318442, Capital = "Dili", Flag = "https://flagcdn.com/w320/tl.png" },
                                new Country { Id = 168, Name = "Vietnam", Population = 97338583, Capital = "Hanoi", Flag = "https://flagcdn.com/w320/vn.png" },
                                new Country { Id = 169, Name = "Uruguay", Population = 3473727, Capital = "Montevideo", Flag = "https://flagcdn.com/w320/uy.png" },
                                new Country { Id = 170, Name = "Vatican City", Population = 451, Capital = "Vatican City", Flag = "https://flagcdn.com/w320/va.png" },
                                new Country { Id = 171, Name = "Hong Kong", Population = 7500700, Capital = "City of Victoria", Flag = "https://flagcdn.com/w320/hk.png" },
                                new Country { Id = 172, Name = "Austria", Population = 8917205, Capital = "Vienna", Flag = "https://flagcdn.com/w320/at.png" },
                                new Country { Id = 173, Name = "Antigua and Barbuda", Population = 97928, Capital = "Saint John's", Flag = "https://flagcdn.com/w320/ag.png" },
                                new Country { Id = 174, Name = "Turkmenistan", Population = 6031187, Capital = "Ashgabat", Flag = "https://flagcdn.com/w320/tm.png" },
                                new Country { Id = 175, Name = "Mozambique", Population = 31255435, Capital = "Maputo", Flag = "https://flagcdn.com/w320/mz.png" },
                                new Country { Id = 176, Name = "Panama", Population = 4314768, Capital = "Panama City", Flag = "https://flagcdn.com/w320/pa.png" },
                                new Country { Id = 177, Name = "Micronesia", Population = 115021, Capital = "Palikir", Flag = "https://flagcdn.com/w320/fm.png" },
                                new Country { Id = 178, Name = "Ireland", Population = 4994724, Capital = "Dublin", Flag = "https://flagcdn.com/w320/ie.png" },
                                new Country { Id = 179, Name = "Curaçao", Population = 155014, Capital = "Willemstad", Flag = "https://flagcdn.com/w320/cw.png" },
                                new Country { Id = 180, Name = "French Guiana", Population = 254541, Capital = "Cayenne", Flag = "https://flagcdn.com/w320/gf.png" },
                                new Country { Id = 181, Name = "Norway", Population = 5379475, Capital = "Oslo", Flag = "https://flagcdn.com/w320/no.png" },
                                new Country { Id = 182, Name = "Åland Islands", Population = 29458, Capital = "Mariehamn", Flag = "https://flagcdn.com/w320/ax.png" },
                                new Country { Id = 183, Name = "Central African Republic", Population = 4829764, Capital = "Bangui", Flag = "https://flagcdn.com/w320/cf.png" },
                                new Country { Id = 184, Name = "Burkina Faso", Population = 20903278, Capital = "Ouagadougou", Flag = "https://flagcdn.com/w320/bf.png" },
                                new Country { Id = 185, Name = "Eritrea", Population = 5352000, Capital = "Asmara", Flag = "https://flagcdn.com/w320/er.png" },
                                new Country { Id = 186, Name = "Tanzania", Population = 59734213, Capital = "Dodoma", Flag = "https://flagcdn.com/w320/tz.png" },
                                new Country { Id = 187, Name = "South Korea", Population = 51780579, Capital = "Seoul", Flag = "https://flagcdn.com/w320/kr.png" },
                                new Country { Id = 188, Name = "Jordan", Population = 10203140, Capital = "Amman", Flag = "https://flagcdn.com/w320/jo.png" },
                                new Country { Id = 189, Name = "Mauritania", Population = 4649660, Capital = "Nouakchott", Flag = "https://flagcdn.com/w320/mr.png" },
                                new Country { Id = 190, Name = "Lithuania", Population = 2794700, Capital = "Vilnius", Flag = "https://flagcdn.com/w320/lt.png" },
                                new Country { Id = 191, Name = "United States Minor Outlying Islands", Population = 300, Capital = "Washington DC", Flag = "https://flagcdn.com/w320/um.png" },
                                new Country { Id = 192, Name = "Slovakia", Population = 5458827, Capital = "Bratislava", Flag = "https://flagcdn.com/w320/sk.png" },
                                new Country { Id = 193, Name = "Angola", Population = 32866268, Capital = "Luanda", Flag = "https://flagcdn.com/w320/ao.png" },
                                new Country { Id = 194, Name = "Kazakhstan", Population = 18754440, Capital = "Nur-Sultan", Flag = "https://flagcdn.com/w320/kz.png" },
                                new Country { Id = 195, Name = "Moldova", Population = 2617820, Capital = "Chi?inau", Flag = "https://flagcdn.com/w320/md.png" },
                                new Country { Id = 196, Name = "Mali", Population = 20250834, Capital = "Bamako", Flag = "https://flagcdn.com/w320/ml.png" },
                                new Country { Id = 197, Name = "Falkland Islands", Population = 2563, Capital = "Stanley", Flag = "https://flagcdn.com/w320/fk.png" },
                                new Country { Id = 198, Name = "Armenia", Population = 2963234, Capital = "Yerevan", Flag = "https://flagcdn.com/w320/am.png" },
                                new Country { Id = 199, Name = "Samoa", Population = 198410, Capital = "Apia", Flag = "https://flagcdn.com/w320/ws.png" },
                                new Country { Id = 200, Name = "Jersey", Population = 100800, Capital = "Saint Helier", Flag = "https://flagcdn.com/w320/je.png" },
                                new Country { Id = 201, Name = "Japan", Population = 125836021, Capital = "Tokyo", Flag = "https://flagcdn.com/w320/jp.png" },
                                new Country { Id = 202, Name = "Bolivia", Population = 11673029, Capital = "Sucre", Flag = "https://flagcdn.com/w320/bo.png" },
                                new Country { Id = 203, Name = "Chile", Population = 19116209, Capital = "Santiago", Flag = "https://flagcdn.com/w320/cl.png" },
                                new Country { Id = 204, Name = "United States", Population = 329484123, Capital = "Washington", Flag = "https://flagcdn.com/w320/us.png" },
                                new Country { Id = 205, Name = "Saint Vincent and the Grenadines", Population = 110947, Capital = "Kingstown", Flag = "https://flagcdn.com/w320/vc.png" },
                                new Country { Id = 206, Name = "Bermuda", Population = 63903, Capital = "Hamilton", Flag = "https://flagcdn.com/w320/bm.png" },
                                new Country { Id = 207, Name = "Seychelles", Population = 98462, Capital = "Victoria", Flag = "https://flagcdn.com/w320/sc.png" },
                                new Country { Id = 208, Name = "British Indian Ocean Territory", Population = 3000, Capital = "Diego Garcia", Flag = "https://flagcdn.com/w320/io.png" },
                                new Country { Id = 209, Name = "Guatemala", Population = 16858333, Capital = "Guatemala City", Flag = "https://flagcdn.com/w320/gt.png" },
                                new Country { Id = 210, Name = "Ecuador", Population = 17643060, Capital = "Quito", Flag = "https://flagcdn.com/w320/ec.png" },
                                new Country { Id = 211, Name = "Martinique", Population = 378243, Capital = "Fort-de-France", Flag = "https://flagcdn.com/w320/mq.png" },
                                new Country { Id = 212, Name = "Tajikistan", Population = 9537642, Capital = "Dushanbe", Flag = "https://flagcdn.com/w320/tj.png" },
                                new Country { Id = 213, Name = "Malta", Population = 525285, Capital = "Valletta", Flag = "https://flagcdn.com/w320/mt.png" },
                                new Country { Id = 214, Name = "Gambia", Population = 2416664, Capital = "Banjul", Flag = "https://flagcdn.com/w320/gm.png" },
                                new Country { Id = 215, Name = "Nigeria", Population = 206139587, Capital = "Abuja", Flag = "https://flagcdn.com/w320/ng.png" },
                                new Country { Id = 216, Name = "Bahamas", Population = 393248, Capital = "Nassau", Flag = "https://flagcdn.com/w320/bs.png" },
                                new Country { Id = 217, Name = "Kosovo", Population = 1775378, Capital = "Pristina", Flag = "https://flagcdn.com/w320/xk.png" },
                                new Country { Id = 218, Name = "Kuwait", Population = 4270563, Capital = "Kuwait City", Flag = "https://flagcdn.com/w320/kw.png" },
                                new Country { Id = 219, Name = "Maldives", Population = 540542, Capital = "Malé", Flag = "https://flagcdn.com/w320/mv.png" },
                                new Country { Id = 220, Name = "South Sudan", Population = 11193729, Capital = "Juba", Flag = "https://flagcdn.com/w320/ss.png" },
                                new Country { Id = 221, Name = "Iran", Population = 83992953, Capital = "Tehran", Flag = "https://flagcdn.com/w320/ir.png" },
                                new Country { Id = 222, Name = "Albania", Population = 2837743, Capital = "Tirana", Flag = "https://flagcdn.com/w320/al.png" },
                                new Country { Id = 223, Name = "Brazil", Population = 212559409, Capital = "Brasília", Flag = "https://flagcdn.com/w320/br.png" },
                                new Country { Id = 224, Name = "Serbia", Population = 6908224, Capital = "Belgrade", Flag = "https://flagcdn.com/w320/rs.png" },
                                new Country { Id = 225, Name = "Belize", Population = 397621, Capital = "Belmopan", Flag = "https://flagcdn.com/w320/bz.png" },
                                new Country { Id = 226, Name = "Myanmar", Population = 54409794, Capital = "Naypyidaw", Flag = "https://flagcdn.com/w320/mm.png" },
                                new Country { Id = 227, Name = "Bhutan", Population = 771612, Capital = "Thimphu", Flag = "https://flagcdn.com/w320/bt.png" },
                                new Country { Id = 228, Name = "Venezuela", Population = 28435943, Capital = "Caracas", Flag = "https://flagcdn.com/w320/ve.png" },
                                new Country { Id = 229, Name = "Liberia", Population = 5057677, Capital = "Monrovia", Flag = "https://flagcdn.com/w320/lr.png" },
                                new Country { Id = 230, Name = "Jamaica", Population = 2961161, Capital = "Kingston", Flag = "https://flagcdn.com/w320/jm.png" },
                                new Country { Id = 231, Name = "Poland", Population = 37950802, Capital = "Warsaw", Flag = "https://flagcdn.com/w320/pl.png" },
                                new Country { Id = 232, Name = "Cayman Islands", Population = 65720, Capital = "George Town", Flag = "https://flagcdn.com/w320/ky.png" },
                                new Country { Id = 233, Name = "Brunei", Population = 437483, Capital = "Bandar Seri Begawan", Flag = "https://flagcdn.com/w320/bn.png" },
                                new Country { Id = 234, Name = "Comoros", Population = 869595, Capital = "Moroni", Flag = "https://flagcdn.com/w320/km.png" },
                                new Country { Id = 235, Name = "Guam", Population = 168783, Capital = "Hagåtña", Flag = "https://flagcdn.com/w320/gu.png" },
                                new Country { Id = 236, Name = "Tonga", Population = 105697, Capital = "Nuku'alofa", Flag = "https://flagcdn.com/w320/to.png" },
                                new Country { Id = 237, Name = "Kiribati", Population = 119446, Capital = "South Tarawa", Flag = "https://flagcdn.com/w320/ki.png" },
                                new Country { Id = 238, Name = "Ghana", Population = 31072945, Capital = "Accra", Flag = "https://flagcdn.com/w320/gh.png" },
                                new Country { Id = 239, Name = "Chad", Population = 16425859, Capital = "N'Djamena", Flag = "https://flagcdn.com/w320/td.png" },
                                new Country { Id = 240, Name = "Zimbabwe", Population = 14862927, Capital = "Harare", Flag = "https://flagcdn.com/w320/zw.png" },
                                new Country { Id = 241, Name = "Saint Martin", Population = 38659, Capital = "Marigot", Flag = "https://flagcdn.com/w320/mf.png" },
                                new Country { Id = 242, Name = "Mongolia", Population = 3278292, Capital = "Ulan Bator", Flag = "https://flagcdn.com/w320/mn.png" },
                                new Country { Id = 243, Name = "Portugal", Population = 10305564, Capital = "Lisbon", Flag = "https://flagcdn.com/w320/pt.png" },
                                new Country { Id = 244, Name = "American Samoa", Population = 55197, Capital = "Pago Pago", Flag = "https://flagcdn.com/w320/as.png" },
                                new Country { Id = 245, Name = "Republic of the Congo", Population = 5657000, Capital = "Brazzaville", Flag = "https://flagcdn.com/w320/cg.png" },
                                new Country { Id = 246, Name = "Belgium", Population = 11555997, Capital = "Brussels", Flag = "https://flagcdn.com/w320/be.png" },
                                new Country { Id = 247, Name = "Israel", Population = 9216900, Capital = "Jerusalem", Flag = "https://flagcdn.com/w320/il.png" },
                                new Country { Id = 248, Name = "New Zealand", Population = 5084300, Capital = "Wellington", Flag = "https://flagcdn.com/w320/nz.png" },
                                new Country { Id = 249, Name = "Nicaragua", Population = 6624554, Capital = "Managua", Flag = "https://flagcdn.com/w320/ni.png" },
                                new Country { Id = 250, Name = "Anguilla", Population = 13452, Capital = "The Valley", Flag = "https://flagcdn.com/w320/ai.png" }

                );
            base.OnModelCreating(modelBuilder);
        }
    }
}
