INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('South Georgia','30','King Edward Point','https://flagcdn.com/w320/gs.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Grenada','112519','St. George''s','https://flagcdn.com/w320/gd.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Switzerland','8654622','Bern','https://flagcdn.com/w320/ch.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Sierra Leone','7976985','Freetown','https://flagcdn.com/w320/sl.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Hungary','9749763','Budapest','https://flagcdn.com/w320/hu.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Taiwan','23503349','Taipei','https://flagcdn.com/w320/tw.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Wallis and Futuna','11750','Mata-Utu','https://flagcdn.com/w320/wf.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Barbados','287371','Bridgetown','https://flagcdn.com/w320/bb.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Pitcairn Islands','56','Adamstown','https://flagcdn.com/w320/pn.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Ivory Coast','26378275','Yamoussoukro','https://flagcdn.com/w320/ci.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Tunisia','11818618','Tunis','https://flagcdn.com/w320/tn.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Italy','59554023','Rome','https://flagcdn.com/w320/it.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Benin','12123198','Porto-Novo','https://flagcdn.com/w320/bj.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Indonesia','273523621','Jakarta','https://flagcdn.com/w320/id.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Cape Verde','555988','Praia','https://flagcdn.com/w320/cv.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Saint Kitts and Nevis','53192','Basseterre','https://flagcdn.com/w320/kn.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Laos','7275556','Vientiane','https://flagcdn.com/w320/la.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Caribbean Netherlands','25987','Kralendijk','https://flagcdn.com/w320/bq.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Uganda','45741000','Kampala','https://flagcdn.com/w320/ug.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Andorra','77265','Andorra la Vella','https://flagcdn.com/w320/ad.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Burundi','11890781','Gitega','https://flagcdn.com/w320/bi.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('South Africa','59308690','Pretoria','https://flagcdn.com/w320/za.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('France','67391582','Paris','https://flagcdn.com/w320/fr.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Libya','6871287','Tripoli','https://flagcdn.com/w320/ly.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Mexico','128932753','Mexico City','https://flagcdn.com/w320/mx.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Gabon','2225728','Libreville','https://flagcdn.com/w320/ga.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Northern Mariana Islands','57557','Saipan','https://flagcdn.com/w320/mp.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('North Macedonia','2077132','Skopje','https://flagcdn.com/w320/mk.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('China','1402112000','Beijing','https://flagcdn.com/w320/cn.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Yemen','29825968','Sana''a','https://flagcdn.com/w320/ye.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Saint Barthélemy','4255','Gustavia','https://flagcdn.com/w320/bl.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Guernsey','62999','St. Peter Port','https://flagcdn.com/w320/gg.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Solomon Islands','686878','Honiara','https://flagcdn.com/w320/sb.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Svalbard and Jan Mayen','2562','Longyearbyen','https://flagcdn.com/w320/sj.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Faroe Islands','48865','Tórshavn','https://flagcdn.com/w320/fo.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Uzbekistan','34232050','Tashkent','https://flagcdn.com/w320/uz.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Egypt','102334403','Cairo','https://flagcdn.com/w320/eg.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Senegal','16743930','Dakar','https://flagcdn.com/w320/sn.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Sri Lanka','21919000','Sri Jayawardenepura Kotte','https://flagcdn.com/w320/lk.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Palestine','4803269','Ramallah','https://flagcdn.com/w320/ps.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Bangladesh','164689383','Dhaka','https://flagcdn.com/w320/bd.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Peru','32971846','Lima','https://flagcdn.com/w320/pe.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Singapore','5685807','Singapore','https://flagcdn.com/w320/sg.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Turkey','84339067','Ankara','https://flagcdn.com/w320/tr.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Afghanistan','40218234','Kabul','https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Aruba','106766','Oranjestad','https://flagcdn.com/w320/aw.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Cook Islands','18100','Avarua','https://flagcdn.com/w320/ck.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('United Kingdom','67215293','London','https://flagcdn.com/w320/gb.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Zambia','18383956','Lusaka','https://flagcdn.com/w320/zm.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Finland','5530719','Helsinki','https://flagcdn.com/w320/fi.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Niger','24206636','Niamey','https://flagcdn.com/w320/ne.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Christmas Island','2072','Flying Fish Cove','https://flagcdn.com/w320/cx.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Tokelau','1411','Fakaofo','https://flagcdn.com/w320/tk.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Guinea-Bissau','1967998','Bissau','https://flagcdn.com/w320/gw.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Azerbaijan','10110116','Baku','https://flagcdn.com/w320/az.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Réunion','840974','Saint-Denis','https://flagcdn.com/w320/re.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Djibouti','988002','Djibouti','https://flagcdn.com/w320/dj.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('North Korea','25778815','Pyongyang','https://flagcdn.com/w320/kp.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Mauritius','1265740','Port Louis','https://flagcdn.com/w320/mu.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Montserrat','4922','Plymouth','https://flagcdn.com/w320/ms.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('United States Virgin Islands','106290','Charlotte Amalie','https://flagcdn.com/w320/vi.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Colombia','50882884','Bogotá','https://flagcdn.com/w320/co.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Greece','10715549','Athens','https://flagcdn.com/w320/gr.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Croatia','4047200','Zagreb','https://flagcdn.com/w320/hr.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Morocco','36910558','Rabat','https://flagcdn.com/w320/ma.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Algeria','44700000','Algiers','https://flagcdn.com/w320/dz.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Antarctica','1000','','https://flagcdn.com/w320/aq.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Netherlands','16655799','Amsterdam','https://flagcdn.com/w320/nl.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Sudan','43849269','Khartoum','https://flagcdn.com/w320/sd.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Fiji','896444','Suva','https://flagcdn.com/w320/fj.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Liechtenstein','38137','Vaduz','https://flagcdn.com/w320/li.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Nepal','29136808','Kathmandu','https://flagcdn.com/w320/np.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Puerto Rico','3194034','San Juan','https://flagcdn.com/w320/pr.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Georgia','3714000','Tbilisi','https://flagcdn.com/w320/ge.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Pakistan','220892331','Islamabad','https://flagcdn.com/w320/pk.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Monaco','39244','Monaco','https://flagcdn.com/w320/mc.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Botswana','2351625','Gaborone','https://flagcdn.com/w320/bw.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Lebanon','6825442','Beirut','https://flagcdn.com/w320/lb.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Papua New Guinea','8947027','Port Moresby','https://flagcdn.com/w320/pg.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Mayotte','226915','Mamoudzou','https://flagcdn.com/w320/yt.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Dominican Republic','10847904','Santo Domingo','https://flagcdn.com/w320/do.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Norfolk Island','2302','Kingston','https://flagcdn.com/w320/nf.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Bouvet Island','0','','https://flagcdn.com/w320/bv.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Qatar','2881060','Doha','https://flagcdn.com/w320/qa.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Madagascar','27691019','Antananarivo','https://flagcdn.com/w320/mg.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('India','1380004385','New Delhi','https://flagcdn.com/w320/in.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Syria','17500657','Damascus','https://flagcdn.com/w320/sy.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Montenegro','621718','Podgorica','https://flagcdn.com/w320/me.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Eswatini','1160164','Mbabane','https://flagcdn.com/w320/sz.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Paraguay','7132530','Asunción','https://flagcdn.com/w320/py.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('El Salvador','6486201','San Salvador','https://flagcdn.com/w320/sv.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Ukraine','44134693','Kyiv','https://flagcdn.com/w320/ua.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Isle of Man','85032','Douglas','https://flagcdn.com/w320/im.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Namibia','2540916','Windhoek','https://flagcdn.com/w320/na.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('United Arab Emirates','9890400','Abu Dhabi','https://flagcdn.com/w320/ae.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Bulgaria','6927288','Sofia','https://flagcdn.com/w320/bg.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Greenland','56367','Nuuk','https://flagcdn.com/w320/gl.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Germany','83240525','Berlin','https://flagcdn.com/w320/de.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Cambodia','16718971','Phnom Penh','https://flagcdn.com/w320/kh.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Iraq','40222503','Baghdad','https://flagcdn.com/w320/iq.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('French Southern and Antarctic Lands','400','Port-aux-Français','https://flagcdn.com/w320/tf.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Sweden','10353442','Stockholm','https://flagcdn.com/w320/se.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Cuba','11326616','Havana','https://flagcdn.com/w320/cu.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Kyrgyzstan','6591600','Bishkek','https://flagcdn.com/w320/kg.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Russia','144104080','Moscow','https://flagcdn.com/w320/ru.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Malaysia','32365998','Kuala Lumpur','https://flagcdn.com/w320/my.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('São Tomé and Príncipe','219161','São Tomé','https://flagcdn.com/w320/st.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Cyprus','1207361','Nicosia','https://flagcdn.com/w320/cy.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Canada','38005238','Ottawa','https://flagcdn.com/w320/ca.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Malawi','19129955','Lilongwe','https://flagcdn.com/w320/mw.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Saudi Arabia','34813867','Riyadh','https://flagcdn.com/w320/sa.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Bosnia and Herzegovina','3280815','Sarajevo','https://flagcdn.com/w320/ba.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Ethiopia','114963583','Addis Ababa','https://flagcdn.com/w320/et.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Spain','47351567','Madrid','https://flagcdn.com/w320/es.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Slovenia','2100126','Ljubljana','https://flagcdn.com/w320/si.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Oman','5106622','Muscat','https://flagcdn.com/w320/om.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Saint Pierre and Miquelon','6069','Saint-Pierre','https://flagcdn.com/w320/pm.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Macau','649342','','https://flagcdn.com/w320/mo.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('San Marino','33938','City of San Marino','https://flagcdn.com/w320/sm.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Lesotho','2142252','Maseru','https://flagcdn.com/w320/ls.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Marshall Islands','59194','Majuro','https://flagcdn.com/w320/mh.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Sint Maarten','40812','Philipsburg','https://flagcdn.com/w320/sx.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Iceland','366425','Reykjavik','https://flagcdn.com/w320/is.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Luxembourg','632275','Luxembourg','https://flagcdn.com/w320/lu.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Argentina','45376763','Buenos Aires','https://flagcdn.com/w320/ar.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Turks and Caicos Islands','38718','Cockburn Town','https://flagcdn.com/w320/tc.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Nauru','10834','Yaren','https://flagcdn.com/w320/nr.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Cocos (Keeling) Islands','544','West Island','https://flagcdn.com/w320/cc.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Western Sahara','510713','El Aaiún','https://flagcdn.com/w320/eh.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Dominica','71991','Roseau','https://flagcdn.com/w320/dm.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Costa Rica','5094114','San José','https://flagcdn.com/w320/cr.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Australia','25687041','Canberra','https://flagcdn.com/w320/au.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Thailand','69799978','Bangkok','https://flagcdn.com/w320/th.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Haiti','11402533','Port-au-Prince','https://flagcdn.com/w320/ht.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Tuvalu','11792','Funafuti','https://flagcdn.com/w320/tv.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Honduras','9904608','Tegucigalpa','https://flagcdn.com/w320/hn.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Equatorial Guinea','1402985','Malabo','https://flagcdn.com/w320/gq.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Saint Lucia','183629','Castries','https://flagcdn.com/w320/lc.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('French Polynesia','280904','Papeetē','https://flagcdn.com/w320/pf.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Belarus','9398861','Minsk','https://flagcdn.com/w320/by.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Latvia','1901548','Riga','https://flagcdn.com/w320/lv.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Palau','18092','Ngerulmud','https://flagcdn.com/w320/pw.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Guadeloupe','400132','Basse-Terre','https://flagcdn.com/w320/gp.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Philippines','109581085','Manila','https://flagcdn.com/w320/ph.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Gibraltar','33691','Gibraltar','https://flagcdn.com/w320/gi.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Denmark','5831404','Copenhagen','https://flagcdn.com/w320/dk.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Cameroon','26545864','Yaoundé','https://flagcdn.com/w320/cm.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Guinea','13132792','Conakry','https://flagcdn.com/w320/gn.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Bahrain','1701583','Manama','https://flagcdn.com/w320/bh.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Suriname','586634','Paramaribo','https://flagcdn.com/w320/sr.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('DR Congo','108407721','Kinshasa','https://flagcdn.com/w320/cd.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Somalia','15893219','Mogadishu','https://flagcdn.com/w320/so.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Czechia','10698896','Prague','https://flagcdn.com/w320/cz.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('New Caledonia','271960','Nouméa','https://flagcdn.com/w320/nc.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Vanuatu','307150','Port Vila','https://flagcdn.com/w320/vu.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Saint Helena','53192','Ascension and Tristan da Cunha','https://flagcdn.com/w320/sh.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Togo','8278737','Lomé','https://flagcdn.com/w320/tg.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('British Virgin Islands','30237','Road Town','https://flagcdn.com/w320/vg.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Kenya','53771300','Nairobi','https://flagcdn.com/w320/ke.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Niue','1470','Alofi','https://flagcdn.com/w320/nu.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Heard Island and McDonald Islands','0','','https://flagcdn.com/w320/hm.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Rwanda','12952209','Kigali','https://flagcdn.com/w320/rw.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Estonia','1331057','Tallinn','https://flagcdn.com/w320/ee.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Romania','19286123','Bucharest','https://flagcdn.com/w320/ro.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Trinidad and Tobago','1399491','Port of Spain','https://flagcdn.com/w320/tt.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Guyana','786559','Georgetown','https://flagcdn.com/w320/gy.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Timor-Leste','1318442','Dili','https://flagcdn.com/w320/tl.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Vietnam','97338583','Hanoi','https://flagcdn.com/w320/vn.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Uruguay','3473727','Montevideo','https://flagcdn.com/w320/uy.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Vatican City','451','Vatican City','https://flagcdn.com/w320/va.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Hong Kong','7500700','City of Victoria','https://flagcdn.com/w320/hk.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Austria','8917205','Vienna','https://flagcdn.com/w320/at.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Antigua and Barbuda','97928','Saint John''s','https://flagcdn.com/w320/ag.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Turkmenistan','6031187','Ashgabat','https://flagcdn.com/w320/tm.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Mozambique','31255435','Maputo','https://flagcdn.com/w320/mz.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Panama','4314768','Panama City','https://flagcdn.com/w320/pa.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Micronesia','115021','Palikir','https://flagcdn.com/w320/fm.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Ireland','4994724','Dublin','https://flagcdn.com/w320/ie.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Curaçao','155014','Willemstad','https://flagcdn.com/w320/cw.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('French Guiana','254541','Cayenne','https://flagcdn.com/w320/gf.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Norway','5379475','Oslo','https://flagcdn.com/w320/no.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Åland Islands','29458','Mariehamn','https://flagcdn.com/w320/ax.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Central African Republic','4829764','Bangui','https://flagcdn.com/w320/cf.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Burkina Faso','20903278','Ouagadougou','https://flagcdn.com/w320/bf.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Eritrea','5352000','Asmara','https://flagcdn.com/w320/er.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Tanzania','59734213','Dodoma','https://flagcdn.com/w320/tz.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('South Korea','51780579','Seoul','https://flagcdn.com/w320/kr.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Jordan','10203140','Amman','https://flagcdn.com/w320/jo.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Mauritania','4649660','Nouakchott','https://flagcdn.com/w320/mr.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Lithuania','2794700','Vilnius','https://flagcdn.com/w320/lt.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('United States Minor Outlying Islands','300','Washington DC','https://flagcdn.com/w320/um.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Slovakia','5458827','Bratislava','https://flagcdn.com/w320/sk.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Angola','32866268','Luanda','https://flagcdn.com/w320/ao.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Kazakhstan','18754440','Nur-Sultan','https://flagcdn.com/w320/kz.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Moldova','2617820','Chișinău','https://flagcdn.com/w320/md.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Mali','20250834','Bamako','https://flagcdn.com/w320/ml.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Falkland Islands','2563','Stanley','https://flagcdn.com/w320/fk.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Armenia','2963234','Yerevan','https://flagcdn.com/w320/am.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Samoa','198410','Apia','https://flagcdn.com/w320/ws.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Jersey','100800','Saint Helier','https://flagcdn.com/w320/je.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Japan','125836021','Tokyo','https://flagcdn.com/w320/jp.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Bolivia','11673029','Sucre','https://flagcdn.com/w320/bo.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Chile','19116209','Santiago','https://flagcdn.com/w320/cl.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('United States','329484123','Washington','https://flagcdn.com/w320/us.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Saint Vincent and the Grenadines','110947','Kingstown','https://flagcdn.com/w320/vc.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Bermuda','63903','Hamilton','https://flagcdn.com/w320/bm.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Seychelles','98462','Victoria','https://flagcdn.com/w320/sc.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('British Indian Ocean Territory','3000','Diego Garcia','https://flagcdn.com/w320/io.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Guatemala','16858333','Guatemala City','https://flagcdn.com/w320/gt.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Ecuador','17643060','Quito','https://flagcdn.com/w320/ec.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Martinique','378243','Fort-de-France','https://flagcdn.com/w320/mq.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Tajikistan','9537642','Dushanbe','https://flagcdn.com/w320/tj.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Malta','525285','Valletta','https://flagcdn.com/w320/mt.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Gambia','2416664','Banjul','https://flagcdn.com/w320/gm.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Nigeria','206139587','Abuja','https://flagcdn.com/w320/ng.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Bahamas','393248','Nassau','https://flagcdn.com/w320/bs.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Kosovo','1775378','Pristina','https://flagcdn.com/w320/xk.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Kuwait','4270563','Kuwait City','https://flagcdn.com/w320/kw.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Maldives','540542','Malé','https://flagcdn.com/w320/mv.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('South Sudan','11193729','Juba','https://flagcdn.com/w320/ss.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Iran','83992953','Tehran','https://flagcdn.com/w320/ir.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Albania','2837743','Tirana','https://flagcdn.com/w320/al.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Brazil','212559409','Brasília','https://flagcdn.com/w320/br.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Serbia','6908224','Belgrade','https://flagcdn.com/w320/rs.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Belize','397621','Belmopan','https://flagcdn.com/w320/bz.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Myanmar','54409794','Naypyidaw','https://flagcdn.com/w320/mm.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Bhutan','771612','Thimphu','https://flagcdn.com/w320/bt.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Venezuela','28435943','Caracas','https://flagcdn.com/w320/ve.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Liberia','5057677','Monrovia','https://flagcdn.com/w320/lr.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Jamaica','2961161','Kingston','https://flagcdn.com/w320/jm.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Poland','37950802','Warsaw','https://flagcdn.com/w320/pl.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Cayman Islands','65720','George Town','https://flagcdn.com/w320/ky.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Brunei','437483','Bandar Seri Begawan','https://flagcdn.com/w320/bn.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Comoros','869595','Moroni','https://flagcdn.com/w320/km.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Guam','168783','Hagåtña','https://flagcdn.com/w320/gu.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Tonga','105697','Nuku''alofa','https://flagcdn.com/w320/to.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Kiribati','119446','South Tarawa','https://flagcdn.com/w320/ki.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Ghana','31072945','Accra','https://flagcdn.com/w320/gh.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Chad','16425859','N''Djamena','https://flagcdn.com/w320/td.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Zimbabwe','14862927','Harare','https://flagcdn.com/w320/zw.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Saint Martin','38659','Marigot','https://flagcdn.com/w320/mf.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Mongolia','3278292','Ulan Bator','https://flagcdn.com/w320/mn.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Portugal','10305564','Lisbon','https://flagcdn.com/w320/pt.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('American Samoa','55197','Pago Pago','https://flagcdn.com/w320/as.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Republic of the Congo','5657000','Brazzaville','https://flagcdn.com/w320/cg.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Belgium','11555997','Brussels','https://flagcdn.com/w320/be.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Israel','9216900','Jerusalem','https://flagcdn.com/w320/il.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('New Zealand','5084300','Wellington','https://flagcdn.com/w320/nz.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Nicaragua','6624554','Managua','https://flagcdn.com/w320/ni.png')
INSERT INTO [dbo].[Countries]([Name],[Population],[Capital],[Flag]) VALUES('Anguilla','13452','The Valley','https://flagcdn.com/w320/ai.png')