name: .NET Core Web App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: ubuntu-24.04  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: FlagExplorer.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: FlagExplorer.Testing\FlagExplorer.Testing.csproj  # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    #- name: Setup MSBuild.exe
    # uses: microsoft/setup-msbuild@v2

    #Add docker support
    - name: Checkout code
      uses: actions/checkout@v2

    #- name: Build Docker image
    #  run: docker build -t mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04 .

    #- name: Run Docker container
    #  run: docker run --name myapp-container -d mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04
        
    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
